version: '3'
services:
  app:
    container_name: online-compiler
    image: online-compiler
    build: ./
    ports:
      - "9999:9999"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=onlineCompiler