version: '3.1'
services:
  app:
    container_name: online-compiler
    image: online-compiler
    build: ./
    ports:
      - "9999:9999"
    depends_on:
      - postgresqldb
      - gcc
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=compilerOnline
  gcc:
    image: gcc